version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_nodejs

  product_service:
    image: v1.1
    container_name: 'product-service'
    ports:
      - "5002:8080"
    depends_on:
      - "rabbitmq"
    links:
      - rabbitmq
    networks: 
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge